# Generated by Django 5.1.1 on 2024-12-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('epost', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=100)),
                ('option_service', models.CharField(choices=[('roof', 'Roof'), ('bathroom', 'Bathroom'), ('kitchen', 'Kitchen'), ('floor', 'Floor'), ('facade', 'Facade'), ('terrace', 'Terrace'), ('window_door_replacement', 'Widow/Door Replacement'), ('garage_door', 'Garage Door'), ('carport', 'Carport'), ('other', 'Other')], default='other', max_length=30)),
                ('job_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
